FROM guacamole/guacamole:0.9.12-incubating

# ARG MYSQL_VER=8.0.19

# ARG DESTINATION=/opt/guacamole

# RUN rm -rf "$DESTINATION/mysql/mysql-connector-java*"
# RUN rm -rf /root/.guacamole/lib/mysql-*
# RUN ls -al "${DESTINATION}/mysql"
# RUN curl -L "https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-${MYSQL_VER}.tar.gz" | \
#     tar -xz                        \
#         -C "$DESTINATION/mysql/"   \
#         --wildcards                \
#         --no-anchored              \
#         --no-wildcards-match-slash \
#         --strip-components=1       \
#         "mysql-connector-*.jar"
# RUN cd /root/.guacamole/lib/ 
# RUN ln -s "${DESTINATION}/mysql/mysql-connector-java-${MYSQL_VER}.jar ."



